port 1194
proto udp
dev tun

ca   /etc/openvpn/ca.crt
cert /etc/openvpn/router1.crt
key  /etc/openvpn/router1.key
dh   /etc/openvpn/dh.pem

tls-auth /etc/openvpn/ta.key 0

server 10.8.0.0 255.255.255.0

push "route 3.2.4.0 255.255.255.0"

cipher AES-128-GCM
ncp-ciphers AES-128-GCM

keepalive 10 120
persist-key
persist-tun

verb 3