client
dev tun
proto udp

remote 6.6.6.1 1194

ca   /etc/openvpn/ca.crt
cert /etc/openvpn/bento.crt
key  /etc/openvpn/bento.key

tls-auth /etc/openvpn/ta.key 1

cipher AES-128-GCM
ncp-ciphers AES-128-GCM

route-nopull
route 3.2.4.0 255.255.255.0

resolv-retry infinite
nobind
persist-key
persist-tun

log /var/log/openvpn/openvpn.log
verb 3
